### ISSUE TITLE
Crashing at Schedule screen

### ISSUE THREAD

**Issue by tm9k1** [pythonindia/PyCon-Mobile-App#53]
Workig on it...

**Comment by brute4s99** [comment]
also integrated mapview
working Schedules screen and fetching from json

**Comment by akshayaurora** [comment]
Resolved.

**Comment by tm9k1** [comment]
Hey @akshayaurora  are you involved in PyConIndia 2023 technical things? I wish to contribute. Please let me know if we can talk over zulipchat.
