### ISSUE TITLE
JSONDecodeError on clicking on Community

### ISSUE THREAD

**Issue by thegauravtiwari** [pythonindia/PyCon-Mobile-App#56]
The error is:
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 13 column 4 (char 619)

**Comment by thegauravtiwari** [comment]
Working on it

**Comment by ritukapatwal** [comment]
done

**Comment by thegauravtiwari** [comment]
NO. Your code only changes the text of some sections and size. Clicking on community gives the same error. Do check it out and make valid PRs. :)

**Comment by ritukapatwal** [comment]
The error I found was "property" attribute missing in JSON file. I added it.

**Comment by thegauravtiwari** [comment]
Yes. But the same error occuring on my system with same changes.

**Comment by ritukapatwal** [comment]
Oh... I wonder why... 
The application worked fine after the changes on my laptop and I got it checked also

**Comment by akshayaurora** [comment]
fixed in fedc803
