### ISSUE TITLE
Last year features

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/PyCon-Mobile-App#6]
### Features
- List Conference schedule in the tabbed view. Each tab displays respective day schedule.
- Clicking on the schedule item or session display the details of the session. All links should be hyperlinked.
- Ability to favorite a session.
- Remind the user 10 minutes before the session.
- User can submit the feedback of the session via app.
- Display the favorite session in a calendar view. 

API: https://github.com/pythonindia/junction/blob/master/docs/api.md
Last year app:  https://play.google.com/store/apps/details?id=com.pyconindia.pycon
Last year app code: https://github.com/pythonindia/PyConIndiaAndroid

**Comment by akshayaurora** [comment]
I have opened separate issues for each feature #9  to  #15
