### ISSUE TITLE
About Page data not consistent

### ISSUE THREAD

**Issue by darthgera123** [pythonindia/PyCon-Mobile-App#65]
The about page is not showing all the data in the json file neither is able to present all the labels properly. I would suggest a look into cards layout
it shows data only on going full screen on PC.
![screenshot from 2018-06-23 14-47-57](https://user-images.githubusercontent.com/30871411/41807960-765c939e-76f4-11e8-872f-24a19f4752c0.png)
to 
![screenshot from 2018-06-23 14-47-45](https://user-images.githubusercontent.com/30871411/41807963-7e507d54-76f4-11e8-8e73-873008535c35.png)

**Comment by akshayaurora** [comment]
fixed in fedc803
