### ISSUE TITLE
Colour theme

### ISSUE THREAD

**Issue by kiok46** [pythonindia/PyCon-Mobile-App#7]
I suggest that app theme should be (Red, Grey) + White.

Just like here: https://in.pycon.org/2016/

```
Red:  
    R: 217
    G: 52
    B: 47

Dark Grey:
    R: 61
    G: 61
    B: 61

Light Grey:
    R: 225
    G: 224
    B: 224

White:
    R: 250
    G: 250
    B: 250
```

**Comment by udiboy1209** [comment]
If these match the colours on the logo, it's perfect

**Comment by kiok46** [comment]
@udiboy1209  Yes! they do.

**Comment by ashishpahwa7** [comment]
@kiok46  Something like this ?

![ff](https://cloud.githubusercontent.com/assets/13049716/16710265/1a8665a8-4646-11e6-86ea-ca59aee1bfaa.png)

**Comment by kiok46** [comment]
@ashishpahwa7 nice job 💃

**Comment by ashishpahwa7** [comment]
Thanks :)

**Comment by ashishpahwa7** [comment]
Opened PR #19

**Comment by kiok46** [comment]
Closing this, since it's out dated and the theme is different this year.
