### ISSUE TITLE
Community page icons unaligned

### ISSUE THREAD

**Issue by DipanshKhandelwal** [pythonindia/PyCon-Mobile-App#86]
![screenshot from 2018-06-23 16-52-04](https://user-images.githubusercontent.com/24923974/41809140-f854e66a-7705-11e8-9184-31d3d8e0a530.png)

**Comment by ritukapatwal** [comment]
![image](https://user-images.githubusercontent.com/29941303/43033526-734bf14e-8ce9-11e8-82d7-290dfe26d066.png)

community page issue resolved

**Comment by akshayaurora** [comment]
![screen shot 2018-09-15 at 4 06 24 am](https://user-images.githubusercontent.com/788023/45578032-c7206c80-b89c-11e8-9a7a-2bd4ac42d931.png)
fixed in new UI, in fedc803
